---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /data

wp_dir: couchdb

proxy_var:
  HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  http_proxy: http://wwwproxy.unimelb.edu.au:8000/
  https_proxy: http://wwwproxy.unimelb.edu.au:8000/
  no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au



# CouchDB configuration
user: admin
pass: "admin"
VERSION: '3.2.1'
cookie: 'a192aeb9904e6590849337933b000c99'

# instance vars
ansible_python_interpreter: /usr/bin/python3
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/team30.pem
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
