# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_flavor: uom.mse.2c9g
instance_key_name: team30

# Volume
volumes:
  - vol_name: server-01
    vol_size: 40
  - vol_name: server-02
    vol_size: 10
  - vol_name: db1-01
    vol_size: 100
  - vol_name: db1-02
    vol_size: 10
  - vol_name: db2-01
    vol_size: 100
  - vol_name: db2-02
    vol_size: 10
  - vol_name: harvester-01
    vol_size: 40
  - vol_name: harvester-02
    vol_size: 10

# Security Group
security_groups:
  - name: ssh
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: http
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: https
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0

  - name: couchDB_1
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: couchDB_2
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0

  - name: couchDB_cluster
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

  - name: react
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: web-server
    volumes: ['server-01', 'server-02']
  - name: db-1
    volumes: [ 'db1-01', 'db1-02' ]
  - name: db-2
    volumes: [ 'db2-01', 'db2-02' ]
  - name: harvester
    volumes: [ 'harvester-01', 'harvester-02' ]
