- name: Clone the code repository into home directory
  git:
    repo: "https://github.com/7elevenk/COMP90024-Team30.git"
    dest: ~/ccc_A2
  environment: "{{ proxy_env }}"
  become: true

# Create Docker config directory
- name: Make sure that Docker config directory exists
  become: yes
  file:
    path: '~/.docker'
    state: 'directory'

# Set Docker proxy for University of Melbourne Research Cloud
- name: Ensure Docker client proxy settings are present on the server
  become: yes
  copy:
    content: "{{ docker_proxy_settings }}"
    dest: ~/.docker/config.json

# Build Docker image for tweet harvester
- name: Build an image and push it to local repo
  docker_image:
    build:
      path: '~/COMP90024-Team30/'
      pull: yes
    name: cloud-assignment-2/tweet-harvester
    tag: latest
    source: build
    force: yes
  become: yes
  environment: "{{ proxy_env }}"

# Stop existing Docker containers for Twitter Harvesters and remove them (if any)
- name: Stop Twitter Harvester Docker container
  become: yes
  docker_container:
    name: twitter-harvester
    state: absent
