# # make sure ccc_A2 directory exists
# - name: ensure the ccc_A2 folder exist
#   become: yes
#   file:
#     path: '/home/ubuntu/ccc_A2'
#     state: 'directory'

# - name: copy the codes and required docker file into folder 
#   copy:
#     src: ~/Downloads/{{ item }}
#     dest: /home/ubuntu/ccc_A2
#     owner: root
#     group: root
#     mode: 0644
#     remote_src: false
#   with_items:
#     - "bne_harv.py"
#     - "melb_harv.py"
#     - "run_harv.sh"
#     - "sydn_harv.py"
#     - "Dockerfile"
#     - "requirements.txt"
#   become: yes

  

# Create Docker config directory
- name: create Docker config directory 
  become: yes
  file:
    path: '~/.docker'
    state: 'directory'

# Set Docker proxy for server
- name: set Docker client proxy settings on MRC server
  become: yes
  copy:
    content: "{{ docker_proxy_setting }}"
    dest: ~/.docker/config.json

# Build Docker image for tweet harvester
- name: Build tweet Harvester docker image
  docker_image:
    build:
      path: '/home/ubuntu/ccc_A2/'
      pull: yes
    name: ccc_a2/tweet_harvester
    tag: latest
    source: build
    force_tag: yes 
  become: yes
  environment: "{{ proxy_env }}"

# Stop existing Docker containers for Twitter Harvesters and remove them (if any existing)
- name: Stop Tweet Harvester Docker container
  become: yes
  docker_container:
    name: tweet_harvester
    state: absent

# Create new docker container for twitter harvester and start the container
- name: Create Tweet Harvester Docker container
  become: yes
  docker_container:
    name: tweet_harvester
    image: ccc_a2/tweet_harvester
    state: started
    pull: false
    recreate: true

# # run the script for harvester
# - name: run the python script for harvester
#   command: ". ./run_harv.sh"
#   become: true
#   run_once: true
