---
- name: Uninstall old versions of docker if any
  become: yes
  apt:
    name: ['docker', 'docker.io','docker-engine']
    state: absent

- name: Install dependencies
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add Docker apt repository 
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name:  update apt cache
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  become: yes
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    state: latest

# Make sure systemd directory exists if not create
- name: Make sure that systemd directory exists
  file:
    path: '/etc/systemd/system'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

# Make sure docker.service.d directory exists if not create one
- name: Make sure that docker.service.d directory exists
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  become: yes

# configure docker proxy for unimelb
- name: Configure Docker proxy
  template:
    src: 'l_http-proxy.conf'
    dest: '/etc/systemd/system/docker.service.d/http-proxy.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ((proxy_env.http_proxy is defined or proxy_env.https_proxy is defined) and ansible_service_mgr == 'systemd')
  become: yes


# Restart Docker daemon
- name: Restart daemon for docker
  command: systemctl restart docker
  become: yes

# Restart systemd daemons
- name: Reload daemons for systemd
  command: systemctl daemon-reload
  become: yes

# Restart Docker for finalised.
- name: Restart docker
  service:
    name: docker
    state: restarted
  become: yes