- hosts: localhost
  vars_files:
    - host_vars/host_var.yaml
  gather_facts: true

  roles:
    - role: openstack-commons
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance