---
- name: Gather facts of remote host
  setup:
    gather_subset: all

# Install dependencies 
- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['git', 'curl', 'vim', 'apt-transport-https', 'build-essential', 'ca-certificates', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common']
    state: latest
    update_cache: yes
    install_recommends: no

  environment: "{{ proxy_env }}"


# Update Python pip
- name: Update python pip
  tags: always
  become: yes
  pip:
    name: ['pip']
    state: latest
  environment: "{{ proxy_env }}"

